# Generated by Django 3.1.1 on 2020-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loosers',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
